import { notFound } from "next/navigation";
import { NextIntlClientProvider, useLocale, useMessages } from "next-intl";

import { CScrollTopButton } from "@/common/components/controls";
import { CMainLayout } from "@/common/components/layouts";
import { IPageProps } from "@/types/page";

import { montserrat, raleway, sourceSerif4 } from "../fonts";

import "./globals.css";

//#region Metadata
export const metadata = {
  title: "Cái web của tui",
  description: "Generated by create next app",
};
//#endregion

interface IRootLayoutProps extends IPageProps {
  children: React.ReactNode;
}

export default function RootLayout({ children, params }: IRootLayoutProps) {
  const locale = useLocale();
  const messages = useMessages();

  if (params.lang !== locale) {
    notFound();
  }

  return (
    <html
      lang={locale}
      className={`${sourceSerif4.variable} ${montserrat.variable} ${raleway.variable}`}
    >
      <body>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <CMainLayout>{children}</CMainLayout>
          <CScrollTopButton />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
