export * from "./MActivities";
export * from "./MContent";
export * from "./MDeanCommittee";
export * from "./MIntroAndTimeline";
export * from "./MQuality";
export * from "./MQualityTeacher";
export * from "./MSubjects";
export * from "./MTrainingDisciplines";
export * from "./MTrainingGoal";
